spring:
  application:
    name: APIStream
  web:
    resources:
      static-locations: "classpath:/public/, classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, file: logs/"
  mvc:
    static-path-pattern: "/APIStreamStaticResources/**"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/
    username: root
    password: "@Dhj114514"
  sql:
    init:
      schema-locations: classpath:db/schema.sql
      mode: always
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    auto-mapping-behavior: full
  global-config:
    enable-sql-runner: true
logging:
  level:
    com:
      daydreamer: debug
  file:
    path: "system/logs"
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7
      clean-history-on-start: true
minio:
  access-key: 1rFgaZJgyyrCgWyzsMYy
  secret-key: mzMiZ5qyVdmsCODPf90As2oHE3Juwrf3eQFOI2i7
  url: http://127.0.0.1:9000
  bucket-name: public